stages:
  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/secom
    outs:
      - data/processed

  features:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/clean_data.csv
    outs:
      - data/features/engineered_data.csv

  train:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/features/engineered_data.csv
    outs:
      - models/rf_model.pkl
      - models/rf_model_features.pkl  # pour éviter les erreurs de feature mismatch

  predict:
    cmd: python src/predict.py
    deps:
      - src/predict.py
      - models/rf_model.pkl
      - models/rf_model_features.pkl
      - data/features/engineered_data.csv
    outs:
      - data/predictions/preds.csv

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/rf_model.pkl
      - models/rf_model_features.pkl
      - data/features/engineered_data.csv
      - data/predictions/preds.csv
    outs:
      - reports/classification_report.txt
